export interface Document {
  id: string;
  title: string;
  description: string;
  price: number;
  course: string;
  subject: string;
  level: string;
  fileType: "PDF" | "DOCX";
  pages: number;
  author: string;
  rating: number;
  reviewCount: number;
  featured: boolean;
  previewText: string;
  createdAt: string;
}

export const courses = [
  "Computer Science",
  "Business Administration",
  "Engineering",
  "Medicine",
  "Law",
  "Mathematics",
  "Psychology",
  "Economics",
];

export const subjects = [
  "Data Structures",
  "Algorithms",
  "Marketing",
  "Accounting",
  "Thermodynamics",
  "Anatomy",
  "Constitutional Law",
  "Linear Algebra",
  "Cognitive Psychology",
  "Microeconomics",
];

export const levels = ["Beginner", "Intermediate", "Advanced"];

export const documents: Document[] = [
  {
    id: "1",
    title: "Complete Data Structures & Algorithms Guide",
    description: "Comprehensive study notes covering arrays, linked lists, trees, graphs, sorting, searching, and dynamic programming with detailed examples and practice problems.",
    price: 12.99,
    course: "Computer Science",
    subject: "Data Structures",
    level: "Intermediate",
    fileType: "PDF",
    pages: 87,
    author: "Dr. Sarah Chen",
    rating: 4.8,
    reviewCount: 234,
    featured: true,
    previewText: "Chapter 1: Introduction to Data Structures\n\nData structures are fundamental building blocks of computer science. They provide organized ways to store, manage, and retrieve data efficiently. Understanding data structures is crucial for writing optimized algorithms and building scalable applications.\n\n1.1 What is a Data Structure?\nA data structure is a specialized format for organizing, processing, retrieving and storing data. It defines not only the data but also the operations that can be performed on the data...",
    createdAt: "2025-11-15",
  },
  {
    id: "2",
    title: "Marketing Fundamentals: Strategy & Analysis",
    description: "In-depth study material covering marketing mix, consumer behavior, segmentation, digital marketing strategies, and brand management with real-world case studies.",
    price: 9.99,
    course: "Business Administration",
    subject: "Marketing",
    level: "Beginner",
    fileType: "PDF",
    pages: 62,
    author: "Prof. James Miller",
    rating: 4.6,
    reviewCount: 189,
    featured: true,
    previewText: "Chapter 1: The Marketing Landscape\n\nMarketing is the process of creating, communicating, delivering, and exchanging offerings that have value for customers, clients, partners, and society at large. In today's dynamic business environment, understanding the fundamentals of marketing is essential for any aspiring business professional...",
    createdAt: "2025-10-20",
  },
  {
    id: "3",
    title: "Thermodynamics: Laws & Applications",
    description: "Detailed lecture notes on the four laws of thermodynamics, entropy, enthalpy, heat engines, and thermodynamic cycles with solved numerical problems.",
    price: 14.99,
    course: "Engineering",
    subject: "Thermodynamics",
    level: "Advanced",
    fileType: "PDF",
    pages: 104,
    author: "Dr. Michael Torres",
    rating: 4.9,
    reviewCount: 156,
    featured: true,
    previewText: "Chapter 1: Fundamental Concepts\n\nThermodynamics is the branch of physics that deals with the relationships between heat and other forms of energy. It describes how thermal energy is converted to and from other forms of energy and how it affects matter. The key concepts include system, surroundings, state properties, and processes...",
    createdAt: "2025-12-01",
  },
  {
    id: "4",
    title: "Human Anatomy: Musculoskeletal System",
    description: "Comprehensive anatomy notes covering bones, joints, muscles, and movement mechanics. Includes labeled diagrams and clinical correlation notes.",
    price: 16.99,
    course: "Medicine",
    subject: "Anatomy",
    level: "Intermediate",
    fileType: "DOCX",
    pages: 93,
    author: "Dr. Emily Watson",
    rating: 4.7,
    reviewCount: 312,
    featured: false,
    previewText: "Section 1: Overview of the Musculoskeletal System\n\nThe musculoskeletal system provides form, support, stability, and movement to the body. It is composed of the bones of the skeleton, muscles, cartilage, tendons, ligaments, joints, and other connective tissue...",
    createdAt: "2025-09-18",
  },
  {
    id: "5",
    title: "Constitutional Law: Rights & Principles",
    description: "Thorough study material on constitutional frameworks, fundamental rights, judicial review, separation of powers, and landmark cases with legal analysis.",
    price: 11.99,
    course: "Law",
    subject: "Constitutional Law",
    level: "Intermediate",
    fileType: "PDF",
    pages: 78,
    author: "Prof. Amanda Richards",
    rating: 4.5,
    reviewCount: 145,
    featured: false,
    previewText: "Chapter 1: Foundations of Constitutional Law\n\nConstitutional law is the body of law which defines the role, powers, and structure of different entities within a state. It encompasses the relationship between different branches of government, and the rights of individuals...",
    createdAt: "2025-08-22",
  },
  {
    id: "6",
    title: "Linear Algebra: Matrices & Transformations",
    description: "Complete notes on vectors, matrices, determinants, eigenvalues, vector spaces, and linear transformations with step-by-step solved examples.",
    price: 10.99,
    course: "Mathematics",
    subject: "Linear Algebra",
    level: "Intermediate",
    fileType: "PDF",
    pages: 71,
    author: "Dr. Robert Kim",
    rating: 4.8,
    reviewCount: 198,
    featured: true,
    previewText: "Chapter 1: Vectors and Vector Spaces\n\nA vector is a mathematical object that has both magnitude and direction. Vectors are used extensively in physics, engineering, and mathematics. In this chapter, we will explore the properties of vectors and introduce the concept of vector spaces...",
    createdAt: "2025-11-05",
  },
  {
    id: "7",
    title: "Cognitive Psychology: Memory & Learning",
    description: "Study notes on perception, attention, memory systems, language processing, problem solving, and cognitive development theories.",
    price: 8.99,
    course: "Psychology",
    subject: "Cognitive Psychology",
    level: "Beginner",
    fileType: "DOCX",
    pages: 55,
    author: "Dr. Lisa Park",
    rating: 4.4,
    reviewCount: 167,
    featured: false,
    previewText: "Chapter 1: Introduction to Cognitive Psychology\n\nCognitive psychology is the scientific study of mental processes such as attention, language use, memory, perception, problem solving, creativity, and reasoning. It emerged in the 1950s as a reaction to behaviorism...",
    createdAt: "2025-10-10",
  },
  {
    id: "8",
    title: "Microeconomics: Markets & Equilibrium",
    description: "Comprehensive notes on supply and demand, market structures, consumer theory, production costs, and game theory fundamentals.",
    price: 13.99,
    course: "Economics",
    subject: "Microeconomics",
    level: "Advanced",
    fileType: "PDF",
    pages: 82,
    author: "Prof. David Nguyen",
    rating: 4.6,
    reviewCount: 203,
    featured: false,
    previewText: "Chapter 1: Principles of Supply and Demand\n\nMicroeconomics studies how individuals and firms make decisions about resource allocation. The fundamental building blocks of microeconomics are supply and demand. Understanding these concepts is essential for analyzing how markets function...",
    createdAt: "2025-12-10",
  },
  {
    id: "9",
    title: "Algorithm Design: Advanced Techniques",
    description: "Advanced algorithmic paradigms including greedy algorithms, divide and conquer, backtracking, branch and bound, and NP-completeness theory.",
    price: 15.99,
    course: "Computer Science",
    subject: "Algorithms",
    level: "Advanced",
    fileType: "PDF",
    pages: 96,
    author: "Dr. Sarah Chen",
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    previewText: "Chapter 1: Algorithmic Paradigms\n\nAlgorithm design is both an art and a science. While there's no universal method for creating algorithms, several powerful paradigms have proven effective across a wide range of problems. In this guide, we explore these paradigms in depth...",
    createdAt: "2026-01-05",
  },
  {
    id: "10",
    title: "Financial Accounting Essentials",
    description: "Study notes covering accounting principles, financial statements, journal entries, ledger accounts, trial balance, and ratio analysis.",
    price: 11.49,
    course: "Business Administration",
    subject: "Accounting",
    level: "Beginner",
    fileType: "PDF",
    pages: 68,
    author: "Prof. Karen Liu",
    rating: 4.3,
    reviewCount: 134,
    featured: false,
    previewText: "Chapter 1: Introduction to Financial Accounting\n\nFinancial accounting is the process of recording, summarizing, and reporting the myriad of transactions resulting from business operations. The financial statements produced through this process provide information about a company's financial position...",
    createdAt: "2025-07-30",
  },
];
